### ISSUE TITLE
Add an additional column in props table for attribute

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-design-system#233]
## Summary

Add an additional column in props table for attribute, in order to allow developers to see both the property and attribute for their web component or React components

## 💬 Description

This may include a re-visit of how our interaction of React/web-component users work, for example, a toggle depending on what type of user you are for code previews, props tables etc. Additionally, we need to consider how component names differ too such as ic-button or IcButton, depending on the technology.

## 💰 Use value

Enable web components users to know their prop name case.

**Comment by DBD324** [comment]
Props table design updated to include new attribute name within the prop name column. All props should display the property as well as the attribute so that they can be used cross-framework. 

Given that a component property exists,
When displaying the prop in the props table,
Then the prop's property and attribute should be visible in the 'Prop name' cell. 

See designs in Figma file: ICDS V2.1/Patterns/Props Table.

**Comment by DBD324** [comment]
Relates to work conducted on #149

**Comment by GCHQ-Developer-112** [comment]
The work for this issue can be found in PR #221
