### ISSUE TITLE
[gatsby]: Investigate and implement how to improve Gatsby build time. 

### ISSUE THREAD

**Issue by jd239** [mi6/ic-design-system#465]
## Summary
When building the guidance site for QA or deployment, build can take around 25+ mins to complete. The can make guidance site updates laborious when it involves created a pr from feature > develop > main.

## 💬 Description

This ticket is to investigate how the build time can be reduced. Gatsby provide a page with details on different aspects of the code to look at: 
- https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/

Just a general search produces additional suggestions. 

NOTE: the following flags have already been tried without much success:
https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/#look-at-current-experimental-flags

## 💰 Use value

Reducing the build time will improve the sustainability of the guidance site as well as improve the release experience for the developer.

**Comment by ad9242** [comment]
some things to resolve spotted in the logs, when pages are pre-rendered:
ic-tab - "messageText": "TypeError: Cannot read property 'setAttribute' of undefined
ic-select/ic-menu - "messageText": "TypeError: this.options.some is not a function\n    at Menu.componentWillLoad

**Comment by GCHQ-Developer-741** [comment]
Update as of 9/6/23:

Work has been done on the [660-review-select-searchbar-tests](https://github.com/mi6/ic-ui-kit/tree/660-review-select-searchbar-tests) branch, which has changes to the gatsby-node.js file to reduce load time of createPages step by reducing the query sizes.

Investigation still needs to be done as the longest task by far is onPostBuild, since it is unclear what is happening during this step.
