### ISSUE TITLE
Determine how to render Material Design icons in Angular apps and add guidance

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-design-system#498]
## Summary
Using Material Design icons in Angular apps involves the `<mat-icon>` component. When slotting this into ICDS components, the icon does not render.

## 💬 Description
It has been reported by an Angular developer that using `<mat-icon>` in ICDS component slots does not render the icon.

This ticket involves determining how to render Angular Material Design icons using `<mat-icon>` in ICDS components and add guidance / make the guidance clearer for Angular developers - probably on the [Icons page](https://design.sis.gov.uk/styles/icons).

## 💰 Use value
This will ensure that developers of Angular apps can use their own icons in ICDS components.

**Comment by GCHQ-Developer-398** [comment]
**Determine how to render Material Design icons in Angular apps and add guidance #498**

_Basic Guide to slot icons into ICDS components_

- Terminal command ng generate component icon
- Copied from https://material.angular.io/components/icon/examples - Thumbs up example HTML copied into icon.component.html and example TS copied into icon.component.ts.
- Moved IconComponent from declaration to import in app.module.ts.
 
Slot does work to render icons, however styling may be difficult to work with.
- I did try fontIcon rather than svgIcon, but it did not work only the name of the icon was being displayed in place of the icon in the angular app.

After finding a method to render material design icons in angular apps, I am happy to close this issue.
