### ISSUE TITLE
Toasts code page to have guidance on queuing 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-design-system#674]
## Summary

Toasts code page should have guidance on queuing Toasts. Currently the site does not show this.

## 💬 Description

A section in the code tab in Toast to demonstrate a queuing of Toasts.

**Comment by GCHQ-Developer-530** [comment]
Completed as part of #675

**Comment by GCHQ-Developer-847** [comment]
We have the "Slotted 'action' toast" example on the [Toast page](https://design.sis.gov.uk/components/toast/code) which has two separate toasts and demonstrates the queueing functionality effectively if you click one and then the other.

-----

The customer for which this ticket was raised was having an issue where multiple auto-dismiss toasts were being displayed but the timer was running down for the ones behind the same time as the one in front. The one behind should wait until the one in front has disappeared. 

@GCHQ-Developer-530 investigated this issue and found that the customer's implementation wasn't quite right - if you call setVisible (soon to be replaced with an equivalent prop) on the toast region rather than directly on a toast (which is what we show in the examples on the website), this makes the queueing of the auto-dismiss toasts behave as it should. The timer for each toast only starts when it is in view. The ticket has been closed because of this - all functionality works correctly.
